<?PHP
////////////////////////////////////////////////
//
//   Smiles List PHPBBS, by Perberos 2006 :3
//
////////////////////////////////////////////////

define('SMILES_DIR', "images/smiles/");

	$array  = array(
		// Foro phpBBs
		" :-D" => SMILES_DIR."icon_biggrin.gif",
		" :D" => SMILES_DIR."icon_biggrin.gif",
		":grin:" => SMILES_DIR."icon_surprised.gif",
		" :)" => SMILES_DIR."icon_smile.gif",
		" :-)" => SMILES_DIR."icon_smile.gif",
		":smile:" => SMILES_DIR."icon_surprised.gif",
		" :(" => SMILES_DIR."icon_sad.gif",
		" :-(" => SMILES_DIR."icon_sad.gif",
		":sad:" => SMILES_DIR."icon_sad.gif",
		" :-o" => SMILES_DIR."icon_surprised.gif",
		":eek:" => SMILES_DIR."icon_eek.gif",
		":shock:" => SMILES_DIR."icon_eek.gif",
		//":???:" => SMILES_DIR."icon_confused.gif",
		":?:" => SMILES_DIR."icon_question.gif",
		" :?" => SMILES_DIR."icon_confused.gif",
		" :-?" => SMILES_DIR."icon_confused.gif",
		" 8)" => SMILES_DIR."icon_cool.gif",
		" 8-)" => SMILES_DIR."icon_cool.gif",
		":cool:" => SMILES_DIR."icon_cool.gif",
		":lol:" => SMILES_DIR."icon_lol.gif",
		" :x" => SMILES_DIR."icon_mad.gif",
		" :-x" => SMILES_DIR."icon_mad.gif",
		":mad:" => SMILES_DIR."icon_mad.gif",
		" :P" => SMILES_DIR."icon_razz.gif",
		" :-P" => SMILES_DIR."icon_razz.gif",
		":razz:" => SMILES_DIR."icon_razz.gif",
		":oops:" => SMILES_DIR."icon_redface.gif",
		" :o" => SMILES_DIR."icon_surprised.gif",
		":cry:" => SMILES_DIR."icon_cry.gif",
		":evil:" => SMILES_DIR."icon_twisted.gif",
		":twisted:" => SMILES_DIR."icon_twisted.gif",
		":roll:" => SMILES_DIR."icon_rolleyes.gif",
		":wink:" => SMILES_DIR."icon_wink.gif",
		" ;)" => SMILES_DIR."icon_wink.gif",
		" ;-)" => SMILES_DIR."icon_wink.gif",
		" :!:" => SMILES_DIR."icon_exclaim.gif",
		":idea:" => SMILES_DIR."icon_idea.gif",
		":arrow:" => SMILES_DIR."icon_arrow.gif",
		" :|" => SMILES_DIR."icon_neutral.gif",
		" :-|" => SMILES_DIR."icon_neutral.gif",
		":neutral:" => SMILES_DIR."icon_neutral.gif",
		" xD" => SMILES_DIR."icon_mrgreen.gif",
		":mrgreen:" => SMILES_DIR."icon_mrgreen.gif",
		" ;p" => SMILES_DIR."icon_razzwink.gif",
		" ;P" => SMILES_DIR."icon_razzwink.gif",
		
		// MSN
		//" :S" => "forum/img/smiles/icon_confused.gif",
		//" :)" => "img/emoticons/",
		//" :D" => "img/emoticons/teeth_smile.gif",
		//" :-o" => "img/emoticons/",
		//" :p" => "img/emoticons/",
		//"(H)" => "img/emoticons/shades_smile.gif",
		//" :@" => "img/emoticons/angry_smile.gif",
		//" :$" => "img/emoticons/embaressed_smile.gif",
		//" :s" => SMILES_DIR."icon_confused.gif", //"img/emoticons/icon_confused.gif",
		//" :(" => "img/emoticons/sad_smile.gif",
		//" :'(" => "img/emoticons/",
		//" :|" => "img/emoticons/",
		//" (6)" => "img/emoticons/",
		//"(A)" => "img/emoticons/angel_smile.gif",
		//"(L)" => "img/emoticons/heart.gif",
		//"(U)" => "img/emoticons/broken_heart.gif",
		//" (M)" => "img/emoticons/",
		//" (@)" => "img/emoticons/",
		//"(&)" => "img/emoticons/bowwow.gif",
		//" (S)" => "img/emoticons/",
		//"(*)" => "img/emoticons/star.gif",
		//" (~)" => "img/emoticons/",
		//"(8) " => "img/emoticons/",
		//" (E)" => "img/emoticons/",
		//" (F)" => "img/emoticons/",
		//" (W)" => "img/emoticons/",
		//" (O)" => "img/emoticons/",
		//"(K)" => "img/emoticons/kiss.gif",
		//" (G)" => "img/emoticons/",
		//" (^)" => "img/emoticons/",
		//" (P)" => "img/emoticons/",
		//" (I)" => "img/emoticons/",
		//" (C)" => "img/emoticons/",
		//" (T)" => "img/emoticons/",
		//" ({)" => "img/emoticons/",
		//" (})" => "img/emoticons/",
		//"(B)" => "img/emoticons/beer_yum.gif",
		//" (D)" => "img/emoticons/",
		//" (Z)" => "img/emoticons/",
		//" (X)" => "img/emoticons/",
		//" (Y)" => "img/emoticons/thumbs_up.gif",
		//"(N)" => "img/emoticons/thumbs_down.gif",
		//" :[" => "img/emoticons/bat.gif",
		//" (nah)" => "img/emoticons/",
		//" (#)" => "img/emoticons/",
		//" (R)" => "img/emoticons/",
		//" :-#" => "img/emoticons/",
		//" 8o|" => "img/emoticons/",
		//" 8-|" => "img/emoticons/",
		//" ^o)" => "img/emoticons/",
		//" :-*" => "img/emoticons/",
		//" +o(" => "img/emoticons/",
		//" (sn)" => "img/emoticons/",
		//" (tu)" => "img/emoticons/",
		//" (pl)" => "img/emoticons/",
		//" (||)" => "img/emoticons/",
		//" (pi)" => "img/emoticons/",
		//" (so)" => "img/emoticons/",
		//" (au)" => "img/emoticons/",
		//" (ap)" => "img/emoticons/",
		//" (um)" => "img/emoticons/",
		//" (ip)" => "img/emoticons/",
		//" (co)" => "img/emoticons/",
		//" (mp)" => "img/emoticons/",
		//" (brb)" => "img/emoticons/",
		//" (st)" => "img/emoticons/",
		//" (h5)" => "img/emoticons/",
		//" (mo)" => "img/emoticons/",
		//" (bah)" => "img/emoticons/",
		//" :^)" => "img/emoticons/",
		//" '-)" => "img/emoticons/",
		//" (li)" => "img/emoticons/",
		//" <:o)" => "img/emoticons/",
		//" 8-)" => "img/emoticons/",
		//" |-)" => "img/emoticons/"
		);

?>