<?php  //config.php :: Archivo de configuracion
// Este archivo es autogenerado | This files is autogenerated
if(!defined("INSIDE")){ die("attemp hacking");}
	$dbsettings = Array(
		"server"        => "localhost", //MySQL server name. (Default: localhost)
		"user"          => "root", // MySQL username.
		"pass"          => "", // GundamMySQL password.
		"name"          => "", // MySQL database name.
		"prefix"        => "wg_", // Prefix for table names.
		"secretword"    => "secret"); // Secret word used when hashing information for cookies.

?>